export const dgym_data = [
  {
    result: {
      standardAdList: [],
      liteAdList: [
        {
          _id: "6049d16b43115b0039222438",
          gymName: "주안 토크짐",
          gymPhotoBig:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/178205a0cce2e241a8/46kiSkh3ckWSzjXNaJBxAFJRqAzYPf25N8k3.센터 Big 복사.jpg",
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/178205a0cce2e241a8/2Y8vJYeagAaLBEmXmNWjcDmL63ZneDm2k5Y5.센터 Small 복사.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.67993543844926, 37.46214685562493],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "수건 / 주차 / WI-FI",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 360000,
            originalPrice: 360000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 4.6,
            count: 10,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
          coupons: null,
        },
        {
          _id: "6406ff7832519b001de7f203",
          gymName: "주안 웨이빗 피트니스",
          gymPhotoBig:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/186bb55efad4519160/2ZvLAZVYZpFmJgVP7MAonAd7SyWTv6pVVYoi.센터 Big 복사.jpg",
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/186bb55efad4519160/gWt1zjjXv6Pni3wbRz5EVkdVurvt3YTJLt.센터 Small 복사.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68053448581358, 37.46127644308608],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "헬스 등록시 PT2회 sv / ‍️그룹 PT월 2회 sv / 개인 샤워실 / 샴푸,바디워시 / 수건 / ️ 수전 / 제빙기 / 공용 락커 / 인바디 / ️ 주차 3시간 가능",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: true,
            lowestPrice: 726000,
            originalPrice: 840000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 8,
          },
          review: {
            rate: 4.95,
            count: 39,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
          coupons: null,
        },
      ],
      centerList: [
        {
          _id: "639189e573286a0493a026a7",
          gymName: "주안 바디에이프",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184f082a87c45b717c/4K8gizpQ5P5vUNbXsgvQZefrmBGqNdDACxM1ECLptmJY.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68329929696361, 37.46634980270749],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T",
          },
          service: {
            free: "주차",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 420000,
            originalPrice: 420000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 3,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6183836e6bdf9700391008e0",
          gymName: "간석 타임짐휘트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce9b9677f4848fa1/4K7xr2pF7kGAM4o2WnmbUVR3MFYu16ERLNeChKbP84oa.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.6961670393311, 37.462191801332374],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "첫 OT 무료",
          },
          service: {
            free: "주차 무료 (무제한) / 수건 / WI-FI",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 360000,
            originalPrice: 360000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 4,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "65d466385e59db001d7fb39a",
          gymName: "주안 바른습관PT",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18dc5af4a825b3b26a/2WjEnPECDZqGKPSQXCe8vNidkUdxjBpoyZwe.센터 Small 복사.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68124444961869, 37.46577213782809],
          isWomenOnly: true,
          isReservationRequired: true,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스"],
          program: {
            free: "",
          },
          service: {
            free: "",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 560000,
            originalPrice: 560000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "5efe103f73ec74570e4699be",
          gymName: "주안 제이짐휘트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/173106f763249e9723/4K7oBqArmMjcZab5mXQkmFY7F16nrXpxQmw2gi48rJK2.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.678965, 37.466364],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "기구필라테스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "운동복 / 수건 / WI-FI",
          },
          price: {
            name: "헬스 + 운동복 or 개인라커",
            count: null,
            isLowestPrice: true,
            lowestPrice: 500000,
            originalPrice: 550000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 5,
          },
          review: {
            rate: 4.65,
            count: 17,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "5a274c0bfe267a29dd5a9170",
          gymName: "주안 홍 휘트니스 24시",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/16029810dca4e4b67a/4K6uHsgyQbSW26b6D671nvqiNaFvXWu9G7EJKxEpRaJb.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.678872, 37.465628],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스"],
          program: {
            free: "O.T (1회)",
          },
          service: {
            free: "수건 / 주차(지상,지하 공용주차) / Wi-fi",
          },
          price: {
            name: "헬스 + 라커",
            count: null,
            isLowestPrice: true,
            lowestPrice: 361000,
            originalPrice: 380000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 19,
          },
          review: {
            rate: 4.97,
            count: 34,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6054002043115b0039223d72",
          gymName: "주안 터닝포인트짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17848207eab348d42e/4K7pC5Rg6XCaxGjpgMDxziwE33hoAbUoYwEYQthMrDBN.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68076795125148, 37.46256169584311],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T", "G.X"],
          program: {
            free: "O.T (1개월 - 1회 / 3~12개월 - 2회)",
          },
          service: {
            free: "운동복 / 수건 / WI-FI / 주차",
          },
          price: {
            name: "헬스 + 운동복/수건 + OT",
            count: null,
            isLowestPrice: false,
            lowestPrice: 480000,
            originalPrice: 480000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 4.44,
            count: 13,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6049b4c343115b00392223c8",
          gymName: "주안 바디제이짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1781fea1ada5b1ee10/4K7pBx166EagmHmJq9wrAuRiq1LCYNjrAjSqJ1qkGt3A.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68471893348678, 37.458437583686504],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "️수건 / Wi-fi",
          },
          price: {
            name: "헬스",
            count: null,
            isLowestPrice: false,
            lowestPrice: 480000,
            originalPrice: 480000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 1,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "613712456bdf9700390959dc",
          gymName: "간석 프로짐휘트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17bbf1f5fdc29135e8/4K7xeHKeUYUXJzLJq61LH2vZZnWbnMwHW9e5g5YEbh3W.jpg",
          address: "인천 남동구 간석동",
          location: [126.71318481761459, 37.46417045938221],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T (기구 사용법 안내 10~ 20분)",
          },
          service: {
            free: "Wi-fi / 수건 / 운동복 / 락커",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: true,
            lowestPrice: 351500,
            originalPrice: 370000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 5,
          },
          review: {
            rate: 5,
            count: 2,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "5aebba95577c700d19593d79",
          gymName: "가좌 다이어트짐86",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/16328d0d7073d1ae53/Small)86.jpg",
          address: "인천 서구 가좌동",
          location: [126.683038, 37.488941],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스"],
          program: {
            free: "",
          },
          service: {
            free: "",
          },
          price: {
            name: "헬스",
            count: null,
            isLowestPrice: false,
            lowestPrice: 500000,
            originalPrice: 500000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 1,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "613704496bdf970039095779",
          gymName: "간석 바디와이짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17bbee8bfb23681784/4K7xeHKAszL3P6tYeDfqawM5G1hf5SQM81rg84Qbi8Y8.jpg",
          address: "인천 남동구 간석동",
          location: [126.71485391560947, 37.4649174534518],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T",
          },
          service: {
            free: "주차 / Wi-fi / 수건",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 396000,
            originalPrice: 396000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 2,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "62f5c8801df81f001dd645fa",
          gymName: "주안 우피짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/182901735e51979a9e/4K8gHiDpW86ASgDNVCchRM8YRLuXU15tyWXQLj6Yxkit.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68007142817409, 37.45256693821056],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T", "기구필라테스"],
          program: {
            free: "",
          },
          service: {
            free: "주차 시간제한 없음",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: true,
            lowestPrice: 474050,
            originalPrice: 499000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 6,
          },
          review: {
            rate: 4.95,
            count: 21,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "634791ca99dc40001d6823a9",
          gymName: "간석 이룸 휘트니스&필라테스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/183cf917f3f23870ce/4K8gXFRHZiMsVGrCD76fQidCTX2tmLesGfUwCkgt5oda.jpg",
          address: "인천 남동구 간석동",
          location: [126.71992409417076, 37.46171874572542],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "기구필라테스", "P.T"],
          program: {
            free: "ot",
          },
          service: {
            free: "주차 시간제한 없음",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 600000,
            originalPrice: 600000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 1,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "65801f1bff3ff10a2de156a8",
          gymName: "가좌 터닝포인트짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18c7c7981a22d98064/2YV3HzYtCQdGuFKyYe8uRPXBNhFHdb7ctdJL.list_photo.jpg",
          address: "인천 서구 가좌동",
          location: [126.6813401, 37.4945936],
          isWomenOnly: false,
          isReservationRequired: true,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스"],
          program: {
            free: "",
          },
          service: {
            free: "️주차 타워 (외제차 불가)",
          },
          price: {
            name: "24시 헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 540000,
            originalPrice: 540000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "5abdf18bd2933c7bb2c27f69",
          gymName: "구월 노블스포렉스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/16275f786f72182648/Small)IMG.jpg",
          address: "인천 남동구 구월동",
          location: [126.700722, 37.44425],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["수영", "헬스", "골프"],
          program: {
            free: "O.T (예약제로 1회 진행 , 기구 이용법 지도) / 수영 단계별 단체 강습",
          },
          service: {
            free: "수건 / 사우나&스파 / 주차 5 시간",
          },
          price: {
            name: "헬스+사우나",
            count: null,
            isLowestPrice: false,
            lowestPrice: 1153000,
            originalPrice: 1153000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 4.81,
            count: 12,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "60add945c70b9e0039951b27",
          gymName: "가좌 아놀드홍짐 가좌홈플러스점",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179a718b7c02847993/4K7pRjxTUZwKniT9jY52APaWBay8xhJmSRQWvRvNcVkU.jpg",
          address: "인천 서구 가좌동",
          location: [126.6706783067134, 37.49758086793603],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "수건 / Wi-fi",
          },
          price: {
            name: "헬스",
            count: null,
            isLowestPrice: true,
            lowestPrice: 450000,
            originalPrice: 600000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 10,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "5a73c5aa6959a655ea649cdb",
          gymName: "부평 더블유짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/161543c22ff45b4645/4K6uVdbJnWndJAmYHdfhiJGFKMyGznaShXc7ckxGwPma.jpg",
          address: "인천 부평구 부평동",
          location: [126.722819, 37.492248],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "스피닝", "그룹P.T"],
          program: {
            free: "O.T (3개월 등록시 1회 / 6개월 등록시 2회)",
          },
          service: {
            free: "주차 (2시간 - SUV/외제차는 제외)",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: true,
            lowestPrice: 324000,
            originalPrice: 349200,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 9,
          },
          review: {
            rate: 4.55,
            count: 23,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "635f3440f2c292001ddbab15",
          gymName: "만수 엑스포스짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1842be41c8b43a24bd/4K8ggeR82xpNwGxxBeBQkcvXfpMues2WwahWU1f9CbgU.jpg",
          address: "인천 남동구 만수동",
          location: [126.7330054979539, 37.461487732334],
          isWomenOnly: true,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "샤워실 / ️ 주차 시간제한 없음",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 396000,
            originalPrice: 396000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 3,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6183671e6bdf97003910046b",
          gymName: "산곡 플랜A피트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce94ad08d5c34447/4K7xr2p8vPEYxHxpJnCkzgQfgoA1CHrTYzpizPBjPa24.jpg",
          address: "인천 부평구 산곡동",
          location: [126.71299418004969, 37.50214891920522],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "탁구", "스쿼시"],
          program: {
            free: "",
          },
          service: {
            free: "주차 150분 / Wi-fi",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 396000,
            originalPrice: 396000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 5,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "64d0d308d7c1bd001d65b785",
          gymName: "부평 키워드핏",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/189cfb859c73854ec6/2WQemZ31hyjcNCtCMSpqjQvFPBsakJxSXmp3.list_photo.jpg",
          address: "인천 부평구 부평동",
          location: [126.7217453, 37.4977424],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "수건 / 락커",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 399000,
            originalPrice: 399000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6482d4a23fcd1a001d875bba",
          gymName: "만수역 어게인핏",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1889f0e9b215434e1d/NtUZkTSDJBAnZo9njcLkEFUhP6ZjwDxJdF.list_photo.jpg",
          address: "인천 남동구 만수동",
          location: [126.73231191532719, 37.45470831594235],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "1:1 PT 체험권",
          },
          service: {
            free: "운동복 / 수건 / 샴푸 / 바디워시",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: true,
            lowestPrice: 220000,
            originalPrice: 240000,
            period: 6,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 3,
          },
          review: {
            rate: 5,
            count: 2,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
      ],
    },
  },
];
