export const dgym_data = [
  {
    result: {
      standardAdList: [],
      liteAdList: [
        {
          _id: "654c5a795b1869001db38133",
          gymName: "부평 스페시맨GYM",
          gymPhotoBig:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18bb2416b9a4aa6cfe/2YCYcqM1JvMNWtKHZmACpYjqRwnPfNStyjje.Big_231121_부평_스페시멘GYM_11.jpg",
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18bb2416b9a4aa6cfe/i7hkxkCheAG42NgYuKnRvg7xJekS6N31fV.Small_231121_부평_스페시멘GYM_11.jpg",
          address: "인천 부평구 부평동",
          location: [126.72364660238469, 37.49293162907103],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["P.T"],
          program: {
            free: "",
          },
          service: {
            free: "️운동복 / ️개인락카 / ️수건 / ️주차 (부평 문화의거리 공영주차장 주차 1시간 무료지원)",
          },
          price: {
            name: "1:1 PT",
            count: 40,
            isLowestPrice: false,
            lowestPrice: 2376000,
            originalPrice: 2376000,
            period: null,
            priceType: "count",
            itemTags: ["P.T"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
          coupons: null,
        },
      ],
      centerList: [
        {
          _id: "62783b62421e32001d56895d",
          gymName: "동암 다짐 휘트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/180a5a7f9ed5435d3/kXjoWZfXJdZNRYGbXr9CPifAqoxGfeDwsEHRjcwzde.jpg",
          address: "인천 부평구 십정동",
          location: [126.70053992247362, 37.47286849040199],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "OT",
          },
          service: {
            free: "수건 / 주차",
          },
          price: {
            name: "헬스 회원권+운동복",
            count: null,
            isLowestPrice: false,
            lowestPrice: 200000,
            originalPrice: 200000,
            period: 6,
            priceType: "period",
            itemTags: [],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 4.57,
            count: 7,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "65ee9ca2b2e9a2001dc1f7e3",
          gymName: "부평남부 바디홀릭 필라테스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e2c13da7355cff1/2ZwYTEgcGbZ7qNpRvcZ4bBEQvCRn7CCmFdff.센터 Small 복사.jpg",
          address: "인천 부평구 부평동",
          location: [126.72463962670848, 37.48733420227458],
          isWomenOnly: false,
          isReservationRequired: true,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["필라테스"],
          program: {
            free: "",
          },
          service: {
            free: "️수건/ 샤워시설 / 반신욕기 / ️공용락커",
          },
          price: {
            name: "6:1 필라테스",
            count: 120,
            isLowestPrice: false,
            lowestPrice: 1160000,
            originalPrice: 1160000,
            period: null,
            priceType: "count",
            itemTags: ["필라테스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "613704496bdf970039095779",
          gymName: "간석 바디와이짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17bbee8bfb23681784/4K7xeHKAszL3P6tYeDfqawM5G1hf5SQM81rg84Qbi8Y8.jpg",
          address: "인천 남동구 간석동",
          location: [126.71485391560947, 37.4649174534518],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T",
          },
          service: {
            free: "주차 / Wi-fi / 수건",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 462000,
            originalPrice: 462000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 2,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "5a73c5aa6959a655ea649cdb",
          gymName: "부평 더블유짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/161543c22ff45b4645/4K6uVdbJnWndJAmYHdfhiJGFKMyGznaShXc7ckxGwPma.jpg",
          address: "인천 부평구 부평동",
          location: [126.722819, 37.492248],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "스피닝", "그룹P.T"],
          program: {
            free: "O.T (3개월 등록시 1회 / 6개월 등록시 2회)",
          },
          service: {
            free: "주차 (2시간 - SUV/외제차는 제외)",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: true,
            lowestPrice: 324000,
            originalPrice: 349200,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 9,
          },
          review: {
            rate: 4.55,
            count: 23,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "62ecab03f9efad001d90bc08",
          gymName: "부평 3세트짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1826c7c068238e39cb/4K8gHar7QpSvsgqithgk5hmGY5XPXTA7K9eCznKvozxx.jpg",
          address: "인천 부평구 부평동",
          location: [126.72501085916447, 37.49093683468285],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["P.T", "헬스"],
          program: {
            free: "기간 선택에 따른 횟수 안내 / 1개월 8회 / 3개월 24회 / 6개월 48회 / 12개월 96회",
          },
          service: {
            free: "락커 / 운동복 / 주차 2시간 가능",
          },
          price: {
            name: "1:1(30분 집중)PT",
            count: 40,
            isLowestPrice: true,
            lowestPrice: 1100000,
            originalPrice: 1150000,
            period: null,
            priceType: "count",
            itemTags: [],
            lowestPriceRemainingCount: 1,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "613712456bdf9700390959dc",
          gymName: "간석 프로짐휘트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17bbf1f5fdc29135e8/4K7xeHKeUYUXJzLJq61LH2vZZnWbnMwHW9e5g5YEbh3W.jpg",
          address: "인천 남동구 간석동",
          location: [126.71318481761459, 37.46417045938221],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T (기구 사용법 안내 10~ 20분)",
          },
          service: {
            free: "Wi-fi / 수건 / 운동복 / 락커",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: true,
            lowestPrice: 351500,
            originalPrice: 370000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 5,
          },
          review: {
            rate: 5,
            count: 2,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "634791ca99dc40001d6823a9",
          gymName: "간석 이룸 휘트니스&필라테스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/183cf917f3f23870ce/4K8gXFRHZiMsVGrCD76fQidCTX2tmLesGfUwCkgt5oda.jpg",
          address: "인천 남동구 간석동",
          location: [126.71992409417076, 37.46171874572542],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "기구필라테스", "P.T"],
          program: {
            free: "ot",
          },
          service: {
            free: "주차 시간제한 없음",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 600000,
            originalPrice: 600000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 1,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "61936a38e271c900398564e1",
          gymName: "부평 PT의정석 운동재활센터",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17d27d6ecb9117de10/4K7y1LZk6uGHeY8uKFvvoerx8vAzcMhZhj9HHeW8fBgt.jpg",
          address: "인천 부평구 부평동",
          location: [126.72394228220516, 37.49672824822733],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["P.T"],
          program: {
            free: "",
          },
          service: {
            free: "수건 / 락커 / Wi-fi",
          },
          price: {
            name: "1:1 P.T (횟수제)",
            count: null,
            isLowestPrice: false,
            lowestPrice: 690000,
            originalPrice: 690000,
            period: 1,
            priceType: "period",
            itemTags: [],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "64d0d308d7c1bd001d65b785",
          gymName: "부평 키워드핏",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/189cfb859c73854ec6/2WQemZ31hyjcNCtCMSpqjQvFPBsakJxSXmp3.list_photo.jpg",
          address: "인천 부평구 부평동",
          location: [126.7217453, 37.4977424],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "수건 / 락커",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 399000,
            originalPrice: 399000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6183836e6bdf9700391008e0",
          gymName: "간석 타임짐휘트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce9b9677f4848fa1/4K7xr2pF7kGAM4o2WnmbUVR3MFYu16ERLNeChKbP84oa.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.6961670393311, 37.462191801332374],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "첫 OT 무료",
          },
          service: {
            free: "주차 무료 (무제한) / 수건 / WI-FI",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 360000,
            originalPrice: 360000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 4,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6183671e6bdf97003910046b",
          gymName: "산곡 플랜A피트니스",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce94ad08d5c34447/4K7xr2p8vPEYxHxpJnCkzgQfgoA1CHrTYzpizPBjPa24.jpg",
          address: "인천 부평구 산곡동",
          location: [126.71299418004969, 37.50214891920522],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "탁구", "스쿼시"],
          program: {
            free: "",
          },
          service: {
            free: "주차 150분 / Wi-fi",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 396000,
            originalPrice: 396000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 5,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "6386b97eb54b10001dec4fe3",
          gymName: "부평 mgym",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184c64497a13d462cd/NV8xnm3W7Lz91cpfB6BB5qKjzHUe7Ws1PP.list_photo.jpg",
          address: "인천 부평구 부평동",
          location: [126.72965251611235, 37.49880655738467],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T",
          },
          service: {
            free: "주차 (2시간)",
          },
          price: {
            name: "헬스",
            count: null,
            isLowestPrice: false,
            lowestPrice: 396000,
            originalPrice: 396000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "5aebba95577c700d19593d79",
          gymName: "가좌 다이어트짐86",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/16328d0d7073d1ae53/Small)86.jpg",
          address: "인천 서구 가좌동",
          location: [126.683038, 37.488941],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스"],
          program: {
            free: "",
          },
          service: {
            free: "",
          },
          price: {
            name: "헬스",
            count: null,
            isLowestPrice: false,
            lowestPrice: 500000,
            originalPrice: 500000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 1,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "643e24eb39376007c698194a",
          gymName: "만수 프로스크린골프연습장",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18792c039cb2ae51ac/4K8hHpX341Yw2ik9S9rbHtcbBjFhzm1uZmxF35aV8D9z.jpg",
          address: "인천 남동구 만수동",
          location: [126.73272028069478, 37.461435279546514],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["골프"],
          program: {
            free: "",
          },
          service: {
            free: "운동복+장갑+운동화 무료대여 / 주차 무료",
          },
          price: {
            name: "연습장 이용권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 900000,
            originalPrice: 900000,
            period: 12,
            priceType: "period",
            itemTags: ["골프"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "635f3440f2c292001ddbab15",
          gymName: "만수 엑스포스짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1842be41c8b43a24bd/4K8ggeR82xpNwGxxBeBQkcvXfpMues2WwahWU1f9CbgU.jpg",
          address: "인천 남동구 만수동",
          location: [126.7330054979539, 37.461487732334],
          isWomenOnly: true,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "샤워실 / ️ 주차 시간제한 없음",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 396000,
            originalPrice: 396000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 2,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "607e39c0c70b9e0039942978",
          gymName: "일신 엘케이짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/178ed1197661950cf3/4K7pEJtywheyiTpxFR77dyrYXAUzUyZ2H6ZF7KydMs6g.jpg",
          address: "인천 부평구 일신동",
          location: [126.74234310156417, 37.48623588383842],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: true,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T (상시지도)",
          },
          service: {
            free: "수건 / 운동복 / 체성분 분석 / Wi-fi / 주차(18시 이후 무료주차)",
          },
          price: {
            name: "헬스+운동복",
            count: null,
            isLowestPrice: true,
            lowestPrice: 329000,
            originalPrice: 363000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: 8,
          },
          review: {
            rate: 5,
            count: 2,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "646f2e430298d1001d1e10c5",
          gymName: "주안 다듬어짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/188524cb7aa3f6590e/2Y8rUU5LkdyrEKRLy72rvHoRaaTYG4yaVYiH.list_photo.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68367654795561, 37.46668869103218],
          isWomenOnly: false,
          isReservationRequired: true,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["P.T"],
          program: {
            free: "상담/체험수업",
          },
          service: {
            free: "주차 2시간 가능 / 공용 락커",
          },
          price: {
            name: "1:1 PT",
            count: 30,
            isLowestPrice: false,
            lowestPrice: 1650000,
            originalPrice: 1650000,
            period: null,
            priceType: "count",
            itemTags: ["P.T"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "615e6c826bdf9700390c9e95",
          gymName: "부개 골드짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17c58d7dcf52f4d98d/4K7xorRJgwgywmRHpZMi7K7cwoVQDFHobqagY4tZmiBi.jpg",
          address: "인천 부평구 부개동",
          location: [126.73837978862596, 37.493667442301806],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "",
          },
          service: {
            free: "",
          },
          price: {
            name: "헬스",
            count: null,
            isLowestPrice: false,
            lowestPrice: 350000,
            originalPrice: 350000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 1,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "639189e573286a0493a026a7",
          gymName: "주안 바디에이프",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184f082a87c45b717c/4K8gizpQ5P5vUNbXsgvQZefrmBGqNdDACxM1ECLptmJY.jpg",
          address: "인천 미추홀구 주안동",
          location: [126.68329929696361, 37.46634980270749],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: true,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["헬스", "P.T"],
          program: {
            free: "O.T",
          },
          service: {
            free: "주차",
          },
          price: {
            name: "헬스 회원권",
            count: null,
            isLowestPrice: false,
            lowestPrice: 420000,
            originalPrice: 420000,
            period: 12,
            priceType: "period",
            itemTags: ["헬스"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 5,
            count: 3,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
        {
          _id: "60c0a19ac70b9e003995a855",
          gymName: "부개 팀타이거복싱짐",
          gymPhotoBig: null,
          gymPhotoSmall:
            "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179f0774361ef22f2/kXYbCnxsTYFHiFCvUChrcYKP1MrhMobhTw2sqAaWLQ.jpg",
          address: "인천 부평구 부개동",
          location: [126.73551054447834, 37.497418727855234],
          isWomenOnly: false,
          isReservationRequired: false,
          hasDailyItem: false,
          isLiked: null,
          isLowestPrice: false,
          exhibitionRemainingCount: null,
          tags: ["복싱"],
          program: {
            free: "G.X (20시)",
          },
          service: {
            free: "Wi-fi / 수건 / 락커",
          },
          price: {
            name: "복싱",
            count: null,
            isLowestPrice: false,
            lowestPrice: 1050000,
            originalPrice: 1050000,
            period: 12,
            priceType: "period",
            itemTags: ["복싱"],
            lowestPriceRemainingCount: null,
          },
          review: {
            rate: 0,
            count: 0,
          },
          videoUrl: null,
          videoThumbnailUrl: null,
        },
      ],
    },
  },
];
